web:
  build: .
  command: sh -c 'npm install; npm start'
  ports:
    - '3000:3000'
  volumes:
   - /home/andres/redis/tp1/api:/api
  links:
    - "db:redis"
db: 
  image: redis
  ports: 
    - "6379:6379"